### ISSUE TITLE
Sirupsen or sirupsen?

### ISSUE THREAD

**Issue by dayfixer** [parkomat/parkomat#13]
`[root@sing2 local]# go get github.com/parkomat/parkomat
go: downloading github.com/parkomat/parkomat v0.0.0-20190302145223-95487e067039
go: github.com/parkomat/parkomat upgrade => v0.0.0-20190302145223-95487e067039
go: finding module for package github.com/Sirupsen/logrus
go: finding module for package golang.org/x/net/webdav
go: finding module for package github.com/BurntSushi/toml
go: finding module for package github.com/miekg/dns
go: downloading golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/miekg/dns v1.1.27
go: downloading github.com/Sirupsen/logrus v1.4.2
go: found github.com/Sirupsen/logrus in github.com/Sirupsen/logrus v1.4.2
go: found github.com/BurntSushi/toml in github.com/BurntSushi/toml v0.3.1
go: found github.com/miekg/dns in github.com/miekg/dns v1.1.27
go: found golang.org/x/net/webdav in golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: github.com/parkomat/parkomat imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
[root@sing2 local]# 
`

**Comment by lbr-dev** [comment]
fixed:https://github.com/parkomat/parkomat/pull/14
